{"name": "Номер заказа появляется в 'В работе'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"1f492b66-58b9-4d09-a236-c8721bd9c83e\")>\ngenerate_random_user = {'email': 'paulevans@example.org', 'name': 'Diane Hood', 'password': '6567811359'}\n\n    @allure.step(\"Логин пользователя на сайте\")\n    @pytest.fixture()\n    def get_authorized(driver, generate_random_user):\n        HeaderPage(driver).click_my_account()\n>       LoginPage(driver).login_user(generate_random_user)\n\nconftest.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:38: in login_user\n    self.wait_for_url_change(old_url)\npages\\base_page.py:58: in wait_for_url_change\n    return WebDriverWait(self.driver, 15).until(expected_conditions.url_changes(old_url))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"1f492b66-58b9-4d09-a236-c8721bd9c83e\")>, method = <function url_changes.<locals>._predicate at 0x000002A6B3B61120>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n.venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "description": "После оформления заказа его номер появляется в разделе 'В работе'", "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1719831174791, "stop": 1719831174791, "uuid": "e53d72dd-ffc3-49bd-bf4a-4d45baf05ca8", "historyId": "d51d283429776315bcb9c6b6742529eb", "testCaseId": "d06606f8dda55f5ec0f6f218d3a5e4a8", "fullName": "tests.test_feed.TestFeed#test_user_order_appear_in_inprogress_feed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed"}, {"name": "subSuite", "value": "TestFeed"}, {"name": "host", "value": "XPMEPODW0067"}, {"name": "thread", "value": "20060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed"}]}